contact_links:
  - name: ğŸ’­ Considerations
    url: https://github.com/hcsolutions/careportal/discussions/new?category=considerations
    about: Please raise enhancement ideas and bug reports as discussions for triage.
  - name: ğŸ“ Proposals
    url: https://github.com/hcsolutions/careportal/discussions/new?category=proposals
    about: Please use Discussions for proposals.
  - name: ğŸ—ï¸ Architecture and Specifications
    url: https://github.com/hcsolutions/careportal/discussions/new?category=architecture-and-specifications
    about: Please use Discussions for architectural documents and specifications.
    
