contact_links:
  - name: ğŸ’­ Considerations
    url: https://github.com/orgs/hcsolutions/projects/8/views/1
    about: Please raise light-touch ideas as draft issues in the backlog for prioritisation.
  - name: ğŸ—ï¸ Architecture and Specifications
    url: https://github.com/hcsolutions/careportal/discussions/new?category=architecture-and-specifications
    about: Please use Discussions for architectural documents and specifications.
    
